- name: "[{{ name }}]: Service deployment"
  block:
    - name: "[{{ name }}]: Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ version }}"
        networks:
          - name: "{{ deploy_network_name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"
