---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Install Docker
      become: true
      block:
        - name: Add universe packages
          ansible.builtin.apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install certificates
          ansible.builtin.apt:
            name:
              - ca-certificates
              - curl
            update-cache: true
            cache_valid_time: 86400

        - name: Folder of the keyrings must be exists
          ansible.builtin.file:
            state: directory
            mode: "0755"
            path: /etc/apt/keyrings

        - name: Install the APT key of Docker's APT repo
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: a+r

        - name: Add Docker APT repository
          ansible.builtin.apt_repository:
            filename: docker
            repo: >
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
              https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update_cache: true
          register: out
        - debug:
            var: out

        - name: Install Docker-ce
          ansible.builtin.apt:
            name: 
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
            update_cache: true

        - name: Start Docker service
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: true

    - name: Final
      become: true
      block:
        - name: Add user to Docker group
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: System reboot
          ansible.builtin.reboot:
