- name: "[{{ name }}]: Secret config"
  ansible.builtin.include_tasks:
    file: "../secret.yml"

- name: "[{{ name }}]: Service deployment"
  block:
    - name: "[{{ name }}]: Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        force_update: true
        networks:
          - name: "{{ deploy_network_name }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"
